services:
  # FastAPI + Nginx를 supervisord로 관리
  fastapi_nginx:
    build: .
    container_name: fastapi_nginx
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./data:/var/www/certbot
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - aqua_network
    restart: unless-stopped
    depends_on:
      - db
      - certbot

  # MySQL DB 서비스
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env  # 🔥 .env 파일 명시적으로 추가
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}  # MySQL 루트 패스워드
      MYSQL_DATABASE: ${RDS_DB_NAME}  # MySQL DB 이름
    ports:
      - "3306:3306"  # DB 포트
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 볼륨

  # Certbot 서비스 (SSL 인증서 관리)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt  # 인증서 저장소
      - ./data:/var/www/certbot  # Certbot 웹 루트
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# MySQL 데이터 영속성을 위한 볼륨
volumes:
  mysql_data:

networks:
  aqua_network:
    driver: bridge
